# environment configuration
settings:
  docker:
    #required_integrations:
    requirements:
      - prophet
      - optuna
      - pandas

# configuration of the Model Control Plane
model:
  name: "prophet_forecaster"
  version: prophet
  description: A simple prophet forecaster
  tags: ["prophet", "forecaster"]

# Configure the pipeline
#parameters:
#  model_type: "rf"  # Choose between rf/sgd
